export { Hero } from "./Hero";
export { About } from "./About";
export { TechStack } from "./TechStack";
export { Projects } from "./Projects";
export { Experience } from "./Experience";
export { Services } from "./Services";
export { Testimonials } from "./Testimonials";
export { Contact } from "./Contact";
export { Footer } from "./Footer";
